kfsism/kfsism/Catalog/Models/ShoreStaffTraining.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoreStaffTraining
    {
        public int ShoreStaffTrainingID { get; set; }
        public string AttendanceSheet { get; set; }
        public string EvaluationSheet { get; set; }
        public Nullable<System.DateTime> Entered_On { get; set; }
        public Nullable<int> Entered_By { get; set; }
    
        public virtual Login Login { get; set; }
    }
}

kfsism/kfsism/Catalog/Controllers/ShoreStaffTrainingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Catalog.Models;
using System.IO;

namespace Catalog.Controllers
{
    public class ShoreStaffTrainingsController : Controller
    {
        private CatalogEntities db = new CatalogEntities();

        // GET: ShoreStaffTrainings
        public ActionResult Index()
        {
            int userid = Convert.ToInt32(Session["UserID"]);
            var ShoreStaffTrainings = db.ShoreStaffTrainings.Where(a => a.Entered_By == userid).Include(t => t.Login);
            return View(ShoreStaffTrainings.ToList());
        }

        // GET: ShoreStaffTrainings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShoreStaffTraining shoreStaffTraining = db.ShoreStaffTrainings.Find(id);
            if (shoreStaffTraining == null)
            {
                return HttpNotFound();
            }
            var UserId = Convert.ToInt32(Session["UserID"]);
            if (shoreStaffTraining.Entered_By != UserId)
            {
                return HttpNotFound();

            }
            return View(shoreStaffTraining);
        }

        // GET: ShoreStaffTrainings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ShoreStaffTrainings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ShoreStaffTrainingID,AttendanceSheet,EvaluationSheet,Entered_On,Entered_By")] ShoreStaffTraining shoreStaffTraining, HttpPostedFileBase AttendanceSheet, HttpPostedFileBase EvaluationSheet)
        {
            if (ModelState.IsValid)
            {
                /*----------------------------File Upload-----------------------------------------*/
                if (AttendanceSheet != null && AttendanceSheet.ContentLength > 0)
                {
                    Random rnd = new Random();
                    int rand = rnd.Next(9999, 99999);
                    // extract only the filename
                    ///// var fileName = Path.GetFileName(Link.FileName);

                    var filenameonly = Path.GetFileNameWithoutExtension(AttendanceSheet.FileName);
                    var fileName = filenameonly + rand + Path.GetExtension(AttendanceSheet.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/TrainingsFilesShoreStaff/Attendance"), fileName);
                    AttendanceSheet.SaveAs(path);
                    shoreStaffTraining.AttendanceSheet = fileName;
                }
                if (EvaluationSheet != null && EvaluationSheet.ContentLength > 0)
                {
                    Random rnd = new Random();
                    int rand = rnd.Next(9999, 99999);
                    // extract only the filename
                    ///// var fileName = Path.GetFileName(Link.FileName);

                    var filenameonly = Path.GetFileNameWithoutExtension(EvaluationSheet.FileName);
                    var fileName = filenameonly + rand + Path.GetExtension(EvaluationSheet.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/TrainingsFilesShoreStaff/Evaluation"), fileName);
                    EvaluationSheet.SaveAs(path);
                    shoreStaffTraining.EvaluationSheet = fileName;
                }
                /*----------------------------File Upload-----------------------------------------*/
                shoreStaffTraining.Entered_By = Convert.ToInt32(Session["UserID"]);
                shoreStaffTraining.Entered_On = DateTime.Now;
                db.ShoreStaffTrainings.Add(shoreStaffTraining);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(shoreStaffTraining);
        }

        // GET: ShoreStaffTrainings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShoreStaffTraining shoreStaffTraining = db.ShoreStaffTrainings.Find(id);
            if (shoreStaffTraining == null)
            {
                return HttpNotFound();
            }
            var UserId = Convert.ToInt32(Session["UserID"]);
            if (shoreStaffTraining.Entered_By != UserId)
            {
                return HttpNotFound();

            }
            return View(shoreStaffTraining);
        }

        // POST: ShoreStaffTrainings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ShoreStaffTrainingID,AttendanceSheet,EvaluationSheet,Entered_On,Entered_By")] ShoreStaffTraining shoreStaffTraining, HttpPostedFileBase AttendanceSheet, HttpPostedFileBase EvaluationSheet)
        {
            if (ModelState.IsValid)
            {
                var shoreStaffTrainings = db.ShoreStaffTrainings.Find(shoreStaffTraining.ShoreStaffTrainingID);

                /*----------------------------File Upload-----------------------------------------*/
                if (AttendanceSheet != null && AttendanceSheet.ContentLength > 0)
                {
                    Random rnd = new Random();
                    int rand = rnd.Next(9999, 99999);
                    // extract only the filename
                    ///// var fileName = Path.GetFileName(Link.FileName);

                    var filenameonly = Path.GetFileNameWithoutExtension(AttendanceSheet.FileName);
                    var fileName = filenameonly + rand + Path.GetExtension(AttendanceSheet.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/TrainingsFiles/Attendance"), fileName);
                    AttendanceSheet.SaveAs(path);
                    shoreStaffTraining.AttendanceSheet = fileName;
                }
                else
                {
                    shoreStaffTraining.AttendanceSheet = shoreStaffTrainings.AttendanceSheet;
                }
                if (EvaluationSheet != null && EvaluationSheet.ContentLength > 0)
                {
                    Random rnd = new Random();
                    int rand = rnd.Next(9999, 99999);
                    // extract only the filename
                    ///// var fileName = Path.GetFileName(Link.FileName);
                    var filenameonly = Path.GetFileNameWithoutExtension(EvaluationSheet.FileName);
                    var fileName = filenameonly + rand + Path.GetExtension(EvaluationSheet.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/TrainingsFiles/Evaluation"), fileName);
                    EvaluationSheet.SaveAs(path);
                    shoreStaffTraining.EvaluationSheet = fileName;
                }
                else
                {
                    shoreStaffTraining.EvaluationSheet = shoreStaffTrainings.EvaluationSheet;
                }
                /*----------------------------File Upload-----------------------------------------*/
                shoreStaffTraining.Entered_By = Convert.ToInt32(Session["UserID"]);
                shoreStaffTraining.Entered_On = DateTime.Now;
                db.Entry(shoreStaffTrainings).State = EntityState.Detached;
                db.Entry(shoreStaffTraining).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(shoreStaffTraining);
        }

        // GET: ShoreStaffTrainings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ShoreStaffTraining shoreStaffTraining = db.ShoreStaffTrainings.Find(id);
            if (shoreStaffTraining == null)
            {
                return HttpNotFound();
            }
            var UserId = Convert.ToInt32(Session["UserID"]);
            if (shoreStaffTraining.Entered_By != UserId)
            {
                return HttpNotFound();

            }
            return View(shoreStaffTraining);
        }

        // POST: ShoreStaffTrainings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ShoreStaffTraining shoreStaffTraining = db.ShoreStaffTrainings.Find(id);
            var UserId = Convert.ToInt32(Session["UserID"]);
            if (shoreStaffTraining.Entered_By != UserId)
            {
                return HttpNotFound();

            }
            db.ShoreStaffTrainings.Remove(shoreStaffTraining);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

kfsism/kfsism/Catalog/Views/ShoreStaffTrainings/Create.cshtml
@model Catalog.Models.ShoreStaffTraining

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    @using (Html.BeginForm("Create", "ShoreStaffTrainings", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>ShoreStaffTraining</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.AttendanceSheet, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.AttendanceSheet, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                                    @Html.ValidationMessageFor(model => model.AttendanceSheet, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.EvaluationSheet, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.EvaluationSheet, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                                    @Html.ValidationMessageFor(model => model.EvaluationSheet, "", new { @class = "text-danger" })
                                </div>
                            </div>



                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

kfsism/kfsism/Catalog/Views/ShoreStaffTrainings/Delete.cshtml
@model Catalog.Models.ShoreStaffTraining

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    <h3>Are you sure you want to delete this?</h3>
                    <div>
                        <h4>ShoreStaffTraining</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.AttendanceSheet)
                            </dt>

                            <dd>
                                <a target="_blank" href="~/TrainingsFilesShoreStaff/Attendance/@Html.DisplayFor(model => model.AttendanceSheet)">View or Download</a>
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.EvaluationSheet)
                            </dt>

                            <dd>
                                <a target="_blank" href="~/TrainingsFilesShoreStaff/Evaluation/@Html.DisplayFor(model => model.EvaluationSheet)">View or Download</a>
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Entered_On)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Entered_On)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Entered_By)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Entered_By)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-default" /> |
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

kfsism/kfsism/Catalog/Views/ShoreStaffTrainings/Details.cshtml
@model Catalog.Models.ShoreStaffTraining

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    <div>
                        <h4>ShoreStaffTraining</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.AttendanceSheet)
                            </dt>
                            <dd>
                                <a target="_blank" href="~/TrainingsFilesShoreStaff/Attendance/@Html.DisplayFor(model => model.AttendanceSheet)">View or Download</a>
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.EvaluationSheet)
                            </dt>

                            <dd>
                                <a target="_blank" href="~/TrainingsFilesShoreStaff/Evaluation/@Html.DisplayFor(model => model.EvaluationSheet)">View or Download</a>
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Entered_On)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Entered_On)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Entered_By)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Entered_By)
                            </dd>

                        </dl>
                    </div>
                    <p>
                        @Html.ActionLink("Edit", "Edit", new { id = Model.ShoreStaffTrainingID }) |
                        @Html.ActionLink("Back to List", "Index")
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

kfsism/kfsism/Catalog/Views/ShoreStaffTrainings/Edit.cshtml
@model Catalog.Models.ShoreStaffTraining

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    @using (Html.BeginForm("Edit", "ShoreStaffTrainings", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>ShoreStaffTraining</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.ShoreStaffTrainingID)

                            <div class="form-group">
                                @Html.LabelFor(model => model.AttendanceSheet, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.AttendanceSheet, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                                    @Html.ValidationMessageFor(model => model.AttendanceSheet, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.EvaluationSheet, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.EvaluationSheet, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                                    @Html.ValidationMessageFor(model => model.EvaluationSheet, "", new { @class = "text-danger" })
                                </div>
                            </div>



                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

kfsism/kfsism/Catalog/Views/ShoreStaffTrainings/Index.cshtml
@model IEnumerable<Catalog.Models.ShoreStaffTraining>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    <p>
                        @Html.ActionLink("Create New", "Create")
                    </p>
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.AttendanceSheet)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.EvaluationSheet)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Entered_On)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Entered_By)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @{ if (item.AttendanceSheet == null)
                {
                                            <a target="" href="">No File</a>

                                        }
                                        else
                                        {
                                            <a target="_blank" href="~/TrainingsFilesShoreStaff/Attendance/@Html.DisplayFor(modelItem => item.AttendanceSheet)">View or Download</a>

                                        }
                                    }

                                </td>
                                <td>
                                    @{ if (item.EvaluationSheet == null)
                {
                                            <a target="" href="">No File</a>

                                        }
                                        else
                                        {
                                            <a target="_blank" href="~/TrainingsFilesShoreStaff/Evaluation/@Html.DisplayFor(modelItem => item.EvaluationSheet)">View or Download</a>

                                        }
                                    }

                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.Entered_On)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Login.Username)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.ShoreStaffTrainingID }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.ShoreStaffTrainingID }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.ShoreStaffTrainingID })
                                </td>
                            </tr>
                                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</section>