kfsism/kfsism/Catalog/Models/Training.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int TrainingID { get; set; }
        public string Training_Topic { get; set; }
        public string Type { get; set; }
        public Nullable<int> Participant_No { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Trainer_Name { get; set; }
        public string Trainer_Desig { get; set; }
        public string Date { get; set; }
        public string Location { get; set; }
        public string Comments { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Entered_On { get; set; }
        public Nullable<int> Entered_By { get; set; }
        public string AttendanceSheet { get; set; }
        public string EvaluationSheet { get; set; }
    
        public virtual Login Login { get; set; }
    }
}

kfsism/kfsism/Catalog/Controllers/TrainingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Catalog.Models;
using System.IO;

namespace Catalog.Controllers
{
    [SessionAuthorize(Roles = "Users,Admin,Assistant,Cordinator,shorestaff,vesselcrew")]

    public class TrainingsController : Controller
    {
        private CatalogEntities db = new CatalogEntities();

        // GET: Trainings
        public ActionResult Index()
        {
            int userid = Convert.ToInt32(Session["UserID"]);
            var trainings = db.Trainings.Where(a=>a.Entered_By==userid).Include(t => t.Login);
            return View(trainings.ToList());
        }

        // GET: Trainings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Training training = db.Trainings.Find(id);
            if (training == null)
            {
                return HttpNotFound();
            }
            var UserId = Convert.ToInt32(Session["UserID"]);
            if (training.Entered_By != UserId)
            {
                return HttpNotFound();

            }
            return View(training);
        }

        // GET: Trainings/Create
        public ActionResult Create()
        {
            ViewBag.Entered_By = new SelectList(db.Logins, "Id", "Username");
            return View();
        }

        // POST: Trainings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Training training, HttpPostedFileBase AttendanceSheet, HttpPostedFileBase EvaluationSheet)
        {
            //if (AttendanceSheet == null || AttendanceSheet.ContentLength <= 0)
            //{
            //    ModelState.AddModelError("AttendanceSheet", "Select File");
            //}
            //if (EvaluationSheet == null || EvaluationSheet.ContentLength <= 0)
            //{
            //    ModelState.AddModelError("EvaluationSheet", "Select File");
            //}

            if (ModelState.IsValid)
            {
                /*----------------------------File Upload-----------------------------------------*/
                if (AttendanceSheet != null && AttendanceSheet.ContentLength > 0)
                {
                    Random rnd = new Random();
                    int rand = rnd.Next(9999, 99999);
                    // extract only the filename
                    ///// var fileName = Path.GetFileName(Link.FileName);

                    var filenameonly = Path.GetFileNameWithoutExtension(AttendanceSheet.FileName);
                    var fileName = filenameonly + rand + Path.GetExtension(AttendanceSheet.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/TrainingsFiles/Attendance"), fileName);
                    AttendanceSheet.SaveAs(path);
                    training.AttendanceSheet = fileName;
                }
                if (EvaluationSheet != null && EvaluationSheet.ContentLength > 0)
                {
                    Random rnd = new Random();
                    int rand = rnd.Next(9999, 99999);
                    // extract only the filename
                    ///// var fileName = Path.GetFileName(Link.FileName);

                    var filenameonly = Path.GetFileNameWithoutExtension(EvaluationSheet.FileName);
                    var fileName = filenameonly + rand + Path.GetExtension(EvaluationSheet.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/TrainingsFiles/Evaluation"), fileName);
                    EvaluationSheet.SaveAs(path);
                    training.EvaluationSheet = fileName;
                }
                /*----------------------------File Upload-----------------------------------------*/
                training.Entered_By = Convert.ToInt32(Session["UserID"]);
                training.Entered_On = DateTime.Now;
                db.Trainings.Add(training);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Entered_By = new SelectList(db.Logins, "Id", "Username", training.Entered_By);
            return View(training);
        }

        // GET: Trainings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Training training = db.Trainings.Find(id);
            if (training == null)
            {
                return HttpNotFound();
            }
            var UserId = Convert.ToInt32(Session["UserID"]);
            if (training.Entered_By != UserId)
            {
                return HttpNotFound();

            }
            ViewBag.Entered_By = new SelectList(db.Logins, "Id", "Username", training.Entered_By);
            return View(training);
        }

        // POST: Trainings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Training training, HttpPostedFileBase AttendanceSheet, HttpPostedFileBase EvaluationSheet)
        {
            if (ModelState.IsValid)
            {
                Training tr = db.Trainings.Find(training.TrainingID);

                /*----------------------------File Upload-----------------------------------------*/
                if (AttendanceSheet != null && AttendanceSheet.ContentLength > 0)
                {
                    Random rnd = new Random();
                    int rand = rnd.Next(9999, 99999);
                    // extract only the filename
                    ///// var fileName = Path.GetFileName(Link.FileName);

                    var filenameonly = Path.GetFileNameWithoutExtension(AttendanceSheet.FileName);
                    var fileName = filenameonly + rand + Path.GetExtension(AttendanceSheet.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/TrainingsFiles/Attendance"), fileName);
                    AttendanceSheet.SaveAs(path);
                    training.AttendanceSheet = fileName;
                }
                else
                {
                   training.AttendanceSheet = tr.AttendanceSheet;
                }
                if (EvaluationSheet != null && EvaluationSheet.ContentLength > 0)
                {
                    Random rnd = new Random();
                    int rand = rnd.Next(9999, 99999);
                    // extract only the filename
                    ///// var fileName = Path.GetFileName(Link.FileName);
                    var filenameonly = Path.GetFileNameWithoutExtension(EvaluationSheet.FileName);
                    var fileName = filenameonly + rand + Path.GetExtension(EvaluationSheet.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/TrainingsFiles/Evaluation"), fileName);
                    EvaluationSheet.SaveAs(path);
                    training.EvaluationSheet = fileName;
                }
                else
                {
                    training.EvaluationSheet = tr.EvaluationSheet;
                }
                /*----------------------------File Upload-----------------------------------------*/
                training.Entered_By = Convert.ToInt32(Session["UserID"]);
                training.Entered_On = DateTime.Now;
                db.Entry(tr).State = EntityState.Detached;

                db.Entry(training).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(training);
        }

        // GET: Trainings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Training training = db.Trainings.Find(id);
          
            if (training == null)
            {
                return HttpNotFound();
            }
            var UserId = Convert.ToInt32(Session["UserID"]);
            if (training.Entered_By != UserId)
            {
                return HttpNotFound();

            }
            return View(training);
        }

        // POST: Trainings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Training training = db.Trainings.Find(id);
            var UserId = Convert.ToInt32(Session["UserID"]);
            if (training.Entered_By != UserId)
            {
                return HttpNotFound();

            }
            db.Trainings.Remove(training);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

kfsism/kfsism/Catalog/Views/Trainings/Create.cshtml
@model Catalog.Models.Training

@{
    if (Session["Role"].ToString() == "Users")
    {
        Layout = "~/Views/Shared/_Layout_user.cshtml";

    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";

    }
}

<section class="content">
    <div class="row">
        <div class="col-xs-10">
            <div class="box">
                <div class="box-header">
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    @using (Html.BeginForm("Create", "Trainings", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>Training</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Training_Topic, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Training_Topic, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Training_Topic, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    <select id="Type" class="form-control" name="Type">
                                        <option value="Training">Training</option>
                                        <option value="Tool Box Talk">Tool Box Talk</option>
                                        <option value="Induction Training">Induction Training</option>
                                    </select>
                                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Participant_No, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Participant_No, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                                    @Html.ValidationMessageFor(model => model.Participant_No, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control",@type="number" } })
                                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-2" for="Training_Hours">Training Hours</label>
                                <div class="col-md-6">
                                    <input class="form-control text-box single-line" id="Training_Hours" name="Training_Hours" type="number" disabled value="">                                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Trainer_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Trainer_Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Trainer_Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Trainer_Desig, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Trainer_Desig, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Trainer_Desig, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Remark, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.AttendanceSheet, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.AttendanceSheet, new { htmlAttributes = new { @class = "form-control" ,@type="file"} })
                                    @Html.ValidationMessageFor(model => model.AttendanceSheet, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.EvaluationSheet, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.EvaluationSheet, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                                    @Html.ValidationMessageFor(model => model.EvaluationSheet, "", new { @class = "text-danger" })
                                </div>
                            </div>



                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-6">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



@section scripts
 {
    <script>
        $(document).ready(function () {
            $("#Participant_No, #Duration").on("change paste keyup", function () {
                $("#Training_Hours").val((($("#Participant_No").val()) * ($("#Duration").val()))/60);
            });

     })
    </script>
}

kfsism/kfsism/Catalog/Views/Trainings/Edit.cshtml
@model Catalog.Models.Training

@{
    if (Session["Role"].ToString() == "Users")
    {
        Layout = "~/Views/Shared/_Layout_user.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<section class="content">
    <div class="row">
        <div class="col-xs-10">
            <div class="box">
                <div class="box-header">
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    @using (Html.BeginForm("Edit", "Trainings", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>Training</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.TrainingID)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Training_Topic, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Training_Topic, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Training_Topic, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    <select id="Type" name="Type" class="form-control">
                                        <option value="Training">Training</option>
                                        <option value="Tool Box Talk">Tool Box Talk</option>
                                        <option value="Induction Training">Induction Training</option>
                                    </select>
                                    @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Participant_No, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Participant_No, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                                    @Html.ValidationMessageFor(model => model.Participant_No, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-2" for="Training_Hours">Training Hours</label>
                                <div class="col-md-6">
                                    <input class="form-control text-box single-line" id="Training_Hours" name="Training_Hours" type="number" disabled value="">                                    @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Trainer_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Trainer_Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Trainer_Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Trainer_Desig, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Trainer_Desig, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Trainer_Desig, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Remark, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.AttendanceSheet, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.AttendanceSheet, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                                    @Html.ValidationMessageFor(model => model.AttendanceSheet, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.EvaluationSheet, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-6">
                                    @Html.EditorFor(model => model.EvaluationSheet, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                                    @Html.ValidationMessageFor(model => model.EvaluationSheet, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-6">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts
 {
    <script>
        $(document).ready(function () {
            $("#Training_Hours").val((($("#Participant_No").val()) * ($("#Duration").val())) / 60);
            $("#Participant_No, #Duration").on("change paste keyup", function () {
                $("#Training_Hours").val((($("#Participant_No").val()) * ($("#Duration").val()))/60);
            });

     })
    </script>
}