kfsism/kfsism/Catalog/Controllers/FormsUploadController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Catalog.Models;
using Catalog.ViewModel;
using System.IO;

namespace Catalog.Controllers
{
    public class FormsUploadController : Controller
    {
        private CatalogEntities db = new CatalogEntities();
        [SessionAuthorize(Roles = "Admin,Assistant,Cordinator")]

        // GET: FormsUpload
        public ActionResult Index()
        {
            ViewBag.Category = new SelectList(db.Categories, "Category_ID", "Name");

            return View(db.Forms.ToList());
        }
        public ActionResult JsonForms(int val = 0)
        {
            ViewBag.Categories = new SelectList(db.Categories.ToList(), "Category_ID", "Name");

            var collection = db.Forms.ToList();
            if (val != 0)
            {
                collection = db.Forms.Where(a => a.Category == val).ToList();
            }

            List<FormViewModel> frms = new List<FormViewModel>();
            foreach (var item in collection)
            {
                FormViewModel frmobj = new FormViewModel();
                frmobj.Id = item.Id;
                frmobj.Name = item.Name;
                frmobj.Link = " <a href='/Files/" + item.Link + "' target='_blank' class='btn btn-labeled btn - success'><span class='btn - label'><i class='fa fa-download'></i></span>Download</a>  ";

                if (Session["Role"].ToString() == "Admin")
                {
                    frmobj.Action = " <a href='/FormsUpload/Delete/" + item.Id + "' class='btn btn-labeled btn - warning'><span class='btn - label'><i class='fa fa-download'></i></span>Delete</a>  ";
                }
                else
                {
                    frmobj.Action = " ";

                }
                frms.Add(frmobj);
            }
            return Json(frms, JsonRequestBehavior.AllowGet);

        }

        // GET: FormsUpload/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Form form = db.Forms.Find(id);
            if (form == null)
            {
                return HttpNotFound();
            }
            return View(form);
        }

        // GET: FormsUpload/Create
        public ActionResult Create()
        {
            ViewBag.Category = new SelectList(db.Categories, "Category_ID", "Name");
            return View();
        }

        // POST: FormsUpload/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Link,Category")] Form form, HttpPostedFileBase Link)
        {
            if (ModelState.IsValid)
            {
                if (Link != null && Link.ContentLength > 0)
                {
                    Random rnd = new Random();
                    int rand = rnd.Next(9999, 99999);
                    // extract only the filename
                    ///// var fileName = Path.GetFileName(Link.FileName);

                    var filenameonly = Path.GetFileNameWithoutExtension(Link.FileName);
                    var fileName = filenameonly + rand + Path.GetExtension(Link.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/Files/Uploads"), fileName);
                    Link.SaveAs(path);
                    form.Link = "Uploads/" + fileName;
                }

                db.Forms.Add(form);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Category = new SelectList(db.Categories, "Category_ID", "Name", form.Category);

            return View(form);
        }

        // GET: FormsUpload/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Form form = db.Forms.Find(id);
            if (form == null)
            {
                return HttpNotFound();
            }
            return View(form);
        }

        // POST: FormsUpload/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Link,Order_O,Category")] Form form)
        {
            if (ModelState.IsValid)
            {
                db.Entry(form).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(form);
        }

        // GET: FormsUpload/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Form form = db.Forms.Find(id);
            if (form == null)
            {
                return HttpNotFound();
            }
            return View(form);
        }

        // POST: FormsUpload/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Form form = db.Forms.Find(id);
            db.Forms.Remove(form);
            string fullPath = Request.MapPath("~/Files/" + form.Link);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

kfsism/kfsism/Catalog/Views/FormsUpload/Create.cshtml
@model Catalog.Models.Form

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content">
    <div class="row">
        <div class="col-xs-10">
            <div class="box">
                <div class="box-header">
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    @using (Html.BeginForm("Create", "FormsUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>Form</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Category, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("Category", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control", @type="file" } })
                                    @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
                                </div>
                            </div>

                       



                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

kfsism/kfsism/Catalog/Views/FormsUpload/Delete.cshtml
@model Catalog.Models.Form

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content">
    <div class="row">
        <div class="col-xs-10">
            <div class="box">
                <div class="box-header">
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <h2>Delete</h2>

                    <h3>Are you sure you want to delete this?</h3>
                    <div>
                        <h4>Form</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Link)
                            </dt>

                            <dd>
                                <a href='/Files/@Model.Link' target='_blank' class='btn btn-labeled btn - success'><span class='btn - label'><i class='fa fa-download'></i></span>Download</a>
                            </dd>



                            <dt>
                                @Html.DisplayNameFor(model => model.Category)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Category1.Name)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-default" /> |
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

kfsism/kfsism/Catalog/Views/FormsUpload/Details.cshtml
@model Catalog.Models.Form

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content">
    <div class="row">
        <div class="col-xs-10">
            <div class="box">
                <div class="box-header">
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <h2>Details</h2>

                    <div>
                        <h4>Form</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Link)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Link)
                            </dd>


                            <dt>
                                @Html.DisplayNameFor(model => model.Category)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Category)
                            </dd>

                        </dl>
                    </div>
                    <p>
                        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
                        @Html.ActionLink("Back to List", "Index")
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

kfsism/kfsism/Catalog/Views/FormsUpload/Edit.cshtml
@model Catalog.Models.Form

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content">
    <div class="row">
        <div class="col-xs-10">
            <div class="box">
                <div class="box-header">
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <h2>Edit</h2>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>Form</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
                                </div>
                            </div>



                            <div class="form-group">
                                @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

kfsism/kfsism/Catalog/Views/FormsUpload/Index.cshtml
@model IEnumerable<Catalog.Models.Form>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content">
    <div class="row">
        <div class="col-xs-12">

            <div class="box">
                <div class="box-header">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Department</label>

                        <div class="col-sm-2">
                            @Html.DropDownList("Category", null,"ALL", htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>


                </div>

                <!-- /.box-header -->
                <div class="box-body">
                    <p>
                        @Html.ActionLink("Create New", "Create")
                    </p>
                    <table class="table" id="table"></table>

                </div>
            </div>
        </div>
    </div>
</section>
@section scripts {

    <script>
        $(document).ready(function () {
            loader(0)
            $("#Category").change(function () {
                loader($(this).val())
            });

            function loader(val) {
                $.ajax({
                    type: 'POST',
                    dataType: 'json',
                    url: '/FormsUpload/JsonForms',
                    data: { val: val },
                    success: function (data) {
                        ///   console.log(data);
                        var table = $('#table').DataTable();
                        table.clear().draw();
                        table.rows.add(data).draw();

                    }
                });
            }
            Table = $('#table').dataTable({
                "pageLength": 25,
                "data": [],
                "columns": [{
                    "title": "Name", 'data': 'Name'
                }, {
                    "title": "Download", 'data': 'Link'
                }, {
                    "title": "Delete", 'data': 'Action'
                }

                ]
            });

        });
    </script>

    }